In [1]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[8]

8

In [6]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [7]:
arr[6:2]

array([], dtype=int32)

In [8]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr[5:]

array([5, 6, 7, 8, 9])

In [10]:
arr[:4] = 100

In [11]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [12]:
arr.arange(0,10)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [13]:
arr = np.arange(0,10)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
slice_of_array = arr[:6]

In [4]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
slice_of_array[:] =11

In [8]:
arr

array([11, 11, 11, 11, 11, 11,  6,  7,  8,  9])

In [9]:
arr_copy =arr.copy()

In [10]:
arr

array([11, 11, 11, 11, 11, 11,  6,  7,  8,  9])

In [11]:
arr_2d = np.array([[2,4,6],[3,6,9],[12,24,36]])

In [12]:
arr_2d

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [12, 24, 36]])

In [13]:
arr_2d[1][2]

9

In [14]:
arr_2d[1][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [15]:
arr_2d[1,2]

9

In [16]:
arr_2d[:2,1:]

array([[4, 6],
       [6, 9]])

In [17]:
arr = np.arange(1,11)

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
bool_arr =arr > 5

In [20]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [22]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [23]:
arr[arr<3]

array([1, 2])

In [24]:
arr_2d = np.arange(50).reshape(5,10)

In [25]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arr_2d[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])