In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np


In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(my_mat[0],my_mat[9])

IndexError: list index out of range

In [13]:
np.arange(my_mat[0],my_mat[9])

IndexError: list index out of range

In [14]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(0,9,5)

array([0, 5])

In [16]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [2]:
np.linspace(0,5,1000)

NameError: name 'np' is not defined

In [1]:
np.eye(3)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.rand(5)

array([0.60011981, 0.82486347, 0.85379252, 0.1872961 , 0.51659703])

In [6]:
np.random.rand(5,5,5)

array([[[1.12939348e-02, 3.91232090e-01, 7.04637679e-01, 9.70115955e-01,
         5.10392159e-01],
        [9.70041687e-01, 1.02458532e-01, 6.07639278e-01, 6.74516478e-01,
         7.88274973e-01],
        [8.12117861e-02, 2.01193919e-01, 5.92395480e-01, 3.92681990e-01,
         1.96041273e-01],
        [1.89302302e-01, 8.13118553e-01, 8.01695095e-03, 8.11191637e-02,
         1.20667029e-01],
        [9.44738395e-01, 1.44109988e-01, 4.78922905e-02, 5.08158826e-01,
         4.06228590e-01]],

       [[7.55376256e-01, 1.04767488e-01, 9.63306940e-01, 5.63132756e-01,
         9.57587377e-01],
        [5.16160320e-01, 5.13959822e-01, 1.30760610e-01, 7.37467179e-02,
         6.47053201e-01],
        [9.25802691e-01, 9.54388392e-01, 2.11307293e-01, 6.30424867e-01,
         2.09914624e-01],
        [1.41433108e-01, 3.28822916e-01, 6.87087869e-01, 5.93958536e-01,
         9.12032524e-01],
        [4.59814004e-01, 7.77994835e-01, 6.05383506e-01, 3.29398939e-01,
         5.76321507e-01]],

      

In [8]:
np.random.randn(5)

array([ 0.93120693,  0.61227608,  0.83156505, -0.24906335,  2.57738433])

In [9]:
np.random.randn(5,4)

array([[ 0.71911478, -1.544893  , -0.63765013, -0.41625923],
       [ 0.3808156 ,  0.47161937,  1.21393594, -0.86957286],
       [-0.14431602,  0.57584281, -0.96045914,  0.28457671],
       [ 0.32827713, -0.20901011, -1.05813005,  0.55072882],
       [-1.25475196,  3.34116688,  0.1258762 ,  0.01665159]])

In [10]:
np.random.randint(1,5)

4

In [11]:
np.random.randint(1,5,8)

array([2, 1, 2, 3, 4, 3, 3, 1])

In [13]:
np.random.randint(1,5,8)

array([3, 4, 2, 2, 1, 4, 4, 1])

In [15]:
arr=np.arange(0,25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
 ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([38, 36,  9, 12, 36, 43, 16, 30, 11,  8])

In [22]:
ranarr.max()

43

In [23]:
ranarr.min()

8

In [1]:
import numpy as np

In [2]:
 ranaar.argmax()

NameError: name 'ranaar' is not defined

In [3]:
ranarr = np.random.randint(0,50,10)


In [4]:
ranaar.argmax()

NameError: name 'ranaar' is not defined

In [7]:
ranarr = np.random.randint(0,50,10)

In [8]:
ranarr

array([36, 26, 20, 12, 21, 17, 40,  4, 49, 16])

In [10]:
ranarr.argmax()

8

In [15]:
ranarr.argmin()

7

In [19]:
arr=np.arange(0,25)


In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr1 = arr.reshape(5,5)

In [22]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr1.shape

(5, 5)